### ISSUE TITLE
Unable to overwrite default WS connection timeout

### ISSUE THREAD

**Issue by rychale** [danschultzer/test_server#13]
Starting a server together with WS endpoint like:

```
{:ok, server} =
  TestServer.start(
    http_server:
      {TestServer.HTTPServer.Plug.Cowboy, protocol_options: [idle_timeout: 60_000]},
    scheme: :https,
    tls: [
      cacertfile: "/tmp/ca-cert.pem",
      certfile: "/tmp/server-cert.pem",
      keyfile: "/tmp/server-key.pem"
    ]
  )

{:ok, ws} = TestServer.websocket_init(server, "/ws")
```

and then connecting to `/ws`. Although the connection is established successfully, the client gets disconnected after a 1-second timeout.

At the same time, the established HTTPS connection doesn't get terminated until a 60-sec interval is passed.

Am I doing something wrong?

Thanks,
Alexey

**Comment by danschultzer** [comment]
I looked at the options, and it shouldn't be necessary to set any since the default already is 60 seconds: https://ninenines.eu/docs/en/cowboy/2.10/manual/cowboy_http2/

What websocket client are you using? I'm using [`Websockex`](https://github.com/Azolo/websockex) in the tests and can't reproduce this. I couldn't even get the websocket to be disconnected but might be a keep alive setting in websockex I need to disable.

**Comment by rychale** [comment]
Oh, I'm sorry. You are right. I'm using Websockex too, but the problem was completely on my side. Thank you for the library!)
