### ISSUE TITLE
Cannot mock 5xx responses

### ISSUE THREAD

**Issue by feld** [danschultzer/test_server#14]
If I try to mock a 5xx response it blows up the entire test. I'm using the Bandit adapter.

e.g.,

```
    TestServer.add("/some/path",
      via: :get,
      to: fn conn ->
        Plug.Conn.send_resp(conn, 500, "")
      end
    )
```

```
14:20:45.892 [error] retry: got response with status 500, will retry in 1000ms, 3 attempts left
warning: ** (RuntimeError) TestServer.Instance #PID<0.628.0> received an unexpected GET request at /some/path.


No active routes. The following routes have been processed:

(list of all the routes here)
```

**Comment by feld** [comment]
I started digging deeper and found the error message is actually from Req.

I'm in the process of attempting to switch a project away from Tesla/Tesla.Mock to Req/TestServer

**Comment by feld** [comment]
I have the solution. If your code expects to be able to do intelligent handling of 408/429/5xx responses you must pass `retry: false` to Req or else this kind of scenario surfaces and you will not be able to validate it in your tests.

Req is batteries included, but this is more than I expected 🥲

Sorry for the noise, hopefully someone else finds this useful.

**Comment by danschultzer** [comment]
Yeah, by default req will retry four times, so yeither ou'll have to add four expectations (could be a small helper function you wrap around `TestServer.add/2`), or add `retry: false` as you did (though that setting should only exist for test env). I think the latter is much better choice because otherwise the test becomes super slow with the throttle that req has on retries.
